import {
  SiHtml5,
  SiCss,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiRedux,
  SiTailwindcss,
  SiGreensock,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiMysql,
  SiFirebase,
  SiGit,
  SiFigma,
  SiGraphql,
  SiPython,
  SiPhp,
  SiRos,
  SiNumpy,
  SiPandas,
  SiPlotly,
  SiOpencv,
  SiLinux,
  SiGooglecloud,
  SiJupyter,
  SiGooglecolab,
  SiPostman,
  SiBootstrap,
  SiVercel,
  SiDocker,
  SiKubernetes,
  SiCplusplus,
  SiC,
} from "react-icons/si";
import {FaJava} from "react-icons/fa";

export const skillsData = [
  // Frontend
  {name: "HTML5", icon: <SiHtml5 />, category: "frontend", color: "#E34F26"},
  {name: "CSS3", icon: <SiCss />, category: "frontend", color: "#1572B6"},
  {
    name: "JavaScript",
    icon: <SiJavascript />,
    category: "frontend",
    color: "#F7DF1E",
  },
  {
    name: "TypeScript",
    icon: <SiTypescript />,
    category: "frontend",
    color: "#3178C6",
  },
  {name: "React.js", icon: <SiReact />, category: "frontend", color: "#61DAFB"},
  {name: "Redux", icon: <SiRedux />, category: "frontend", color: "#764ABC"},
  {
    name: "Tailwind",
    icon: <SiTailwindcss />,
    category: "frontend",
    color: "#06B6D4",
  },
  {name: "GSAP", icon: <SiGreensock />, category: "frontend", color: "#88CE02"},

  // Backend
  {name: "Java", icon: <FaJava />, category: "backend", color: "#007396"},
  {name: "Python", icon: <SiPython />, category: "backend", color: "#3776AB"},
  {
    name: "Node.js",
    icon: <SiNodedotjs />,
    category: "backend",
    color: "#339933",
  },
  {name: "MongoDB", icon: <SiMongodb />, category: "backend", color: "#47A248"},
  {name: "SQL", icon: <SiMysql />, category: "backend", color: "#4479A1"},
  {name: "C++", icon: <SiCplusplus />, category: "backend", color: "#00599C"},
  {name: "C", icon: <SiC />, category: "backend", color: "#A8B9CC"},

  // Ecosystem & AI
  {name: "Docker", icon: <SiDocker />, category: "ecosystem", color: "#2496ED"},
  {name: "Git", icon: <SiGit />, category: "ecosystem", color: "#F05032"},
  {
    name: "Postman",
    icon: <SiPostman />,
    category: "ecosystem",
    color: "#FF6C37",
  },
  {name: "Linux", icon: <SiLinux />, category: "ecosystem", color: "#FCC624"},
  {name: "OpenCV", icon: <SiOpencv />, category: "ecosystem", color: "#5C3EE8"},
  {name: "NumPy", icon: <SiNumpy />, category: "ecosystem", color: "#013243"},
  {name: "Pandas", icon: <SiPandas />, category: "ecosystem", color: "#150458"},
  {name: "Vercel", icon: <SiVercel />, category: "ecosystem", color: "#000000"},
];
